-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgLNwvh/6uEujalYw1
8Ye8uRWgJf7ugsZtBWqvlGhrVoGgCgYIKoZIzj0DAQehRANCAAQatnaofFC52RyS
E6WomHgVCESTsY+h33rdALRHlzERGjTGUcwy9G7HE1FA6IyH/dMe0BMTTCRvHv4J
3/sW+XqF
-----END PRIVATE KEY-----